### ISSUE TITLE
[FR] Filter proxy list to specific country?

### ISSUE THREAD

**Issue by Hukuma1** [DoppelKorn/Youtube-Viewer#1]
Heya. I know this is early, but figured I'd put in a request. I see that the code pulls all the IPs from the free-proxy-list. On that site you have all the regions listed for the IPs. Could you please add a function in your script to target specific region of proxy? (e.g. United States) Useful for smaller Youtube channels to only be receiving views from their own country as a start.

**Comment by soerenpriess** [comment]
Hey, sounds like a good idea. I implemented it immediately. It is now possible to decide if you want to search for proxies from a certain country and can then enter your country code (for example: RU = Russia, FR = France, DE = Germany, ...). However, a free proxy service is offered here, which already has a few that are not working. It may be that this filtering reduces the number of working proxies immensely.
